[project]
name = "llm-med-synth"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "google-genai>=1.3.0",
    "python-dotenv>=1.0.0",
    "numpy>=1.26.4",
    "tqdm>=4.67.1",
]
